project:
  type: website
  output-dir: docs

website:
  page-navigation: true
  title: ""
  favicon: "plot/viserdac-logo.png"
  
  repo-url: https://github.com/vsu-viserdac/r-programming-data-viz-analysis
  site-url: https://vsu-viserdac.github.io/r-programming-data-viz-analysis/
  
  sidebar:
    style: docked
    pinned: true
    search: true
    tools:
      - icon: facebook
        href: https://www.facebook.com/viserdac/
      - icon: globe
        href: https://viserdac.vsu.edu.ph/
      - icon: github
        href: https://github.com/vsu-viserdac/r-programming-data-viz-analysis
    
    contents:
      - href: "index.qmd"
        text: "**Home**"
      - href: "resources.qmd"
        text: "**Resources**"
      - section: "**Day 1 sessions**"
        contents:
          - href: "session-1-getting-started-r.qmd"
            text: "Getting started with R"
          - href: ""
            text: "Workshop 1: Setting up and importing data"
          - href: "session-2-data-wrangling.qmd"
            text: "Data wrangling with Tidyverse"
          - href: ""
            text: "Workshop 2: Cleaning and structuring data"

      
      - section: "**Day 2 sessions**"
        contents:
          - href: "session-3-intro-data-viz.qmd"
            text: "Introduction to Data Visualization with ggplot2"
          - href: ""
            text: "Workshop 3: Visualizing research data"
          - href: "session-4-intro-data-analysis.qmd"
            text: "Introduction to Data analysis with R"
          - href: ""
            text: "Workshop 4: Testing hypotheses in R"
            
      
      - section: "**Day 3 sessions**"
        contents:
          - href: "session-5-intro-regression-analysis.qmd"
            text: "Introduction to Regression Analysis"
          - href: ""
            text: "Workshop 5: Building and checking regression models"
          - href: "session-6-reproducible-report.qmd"
            text: "Building Reproducible Data Analysis Reports in Quarto"
          - href: ""
            text: "Workshop 6: Generating an HTML report"

      
format:
  html:
    theme:
      light: [cosmo, styles.scss]
      dark: [cosmo, dark-style.scss]
    mainfont: "Arial"
    code-copy: true
    code-overflow: wrap
    toc: false

freeze: auto
editor: visual

